[package]
name = "factorial"
version = "0.1.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
description = "Convenient methods to compute the factorial, optionally checked."
repository = "https://github.com/thomwiggers/factorial/"
readme = "README.md"
keywords = ["mathematics", "maths", "factorial", "combinatorics"]
categories = ["science", "algorithms"]
license = "MIT"

[badges]
travis-ci = { repository = "thomwiggers/factorial" }
maintenance = { status = "passively-maintained" }

[dependencies]
num-traits = "0.2"
